version: '3.2'

services:

  mysql:
    image: mysql/mysql-server:8.0.23
    command: --sort-buffer-size=256000000
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=anansi
      - MYSQL_USER=anansi
      - MYSQL_PASSWORD=anansi
    ports:
      - 33061:3306
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass hrLmooHxLCIa
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis
#      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master

  api:
    container_name: anansi_api
    depends_on:
      - mysql
      - redis
    build: api
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
      - ./docker/php/custom-config.ini:/usr/local/etc/php/conf.d/custom-config.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      PHP_ENABLE_XDEBUG: 1

  backend:
    container_name: anansi_backend
    depends_on:
      - mysql
      - redis
    build: backend
    ports:
      - 21080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
      - ./docker/php/custom-config.ini:/usr/local/etc/php/conf.d/custom-config.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      PHP_ENABLE_XDEBUG: 1

  frontend:
    container_name: anansi_frontend
    depends_on:
      - mysql
      - redis
    build: frontend
    ports:
      - 22080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
      - ./docker/php/custom-config.ini:/usr/local/etc/php/conf.d/custom-config.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      PHP_ENABLE_XDEBUG: 1

volumes:
  mysql_data:
  redis_data:
