version: '3.2'

services:

  backend:
    container_name: backend_costeo
    build: backend
    expose:
      - 80
    restart: always
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
      - ./docker/php/custom-config.ini:/usr/local/etc/php/conf.d/custom-config.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.costeoapp-secure.entrypoints=websecure"
      - "traefik.http.routers.costeoapp-secure.rule=Host(`app.sistemapararestaurantes.com`)"
      - "traefik.http.routers.costeoapp-secure.middlewares=user-auth@file"

  frontend:
    #    depends_on:
    #      - pgsql
    container_name: frontend_costeo
    build: frontend
    expose:
      - 80
    restart: always
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
      - ./docker/php/custom-config.ini:/usr/local/etc/php/conf.d/custom-config.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.costeoadmin-secure.entrypoints=websecure"
      - "traefik.http.routers.costeoadmin-secure.rule=Host(`admin.sistemapararestaurantes.com`)"
      - "traefik.http.routers.costeoadmin-secure.middlewares=user-auth@file"

  landing:
    #    depends_on:
    #      - pgsql
    container_name: landing_costeo
    build: landing
    expose:
      - 80
    restart: always
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
      - ./docker/php/custom-config.ini:/usr/local/etc/php/conf.d/custom-config.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.costeo-secure.entrypoints=websecure"
      - "traefik.http.routers.costeo-secure.rule=Host(`sistemapararestaurantes.com`)"
      - "traefik.http.routers.costeo-secure.middlewares=user-auth@file"


networks:
  default:
    external:
      name: proxy
