version: '3.2'

services:

  backend:
    container_name: backend_costeo
    build: backend
    depends:
      - redis
    ports:
      - 8012:80
    restart: always
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
      - ./docker/php/custom-config.ini:/usr/local/etc/php/conf.d/custom-config.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    

  frontend:
    #    depends_on:
    #      - pgsql
    container_name: frontend_costeo
    build: frontend
    ports:
      - 8010:80
    depends:
      - redis
    restart: always
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
      - ./docker/php/custom-config.ini:/usr/local/etc/php/conf.d/custom-config.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    

  landing:
    #    depends_on:
    #      - pgsql
    container_name: landing_costeo
    build: landing
    ports:
      - 8009:80
    depends:
      - redis
    restart: always
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
      - ./docker/php/custom-config.ini:/usr/local/etc/php/conf.d/custom-config.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini


  redis:
    image: "redis:alpine"
    command: redis-server --requirepass hrLmooHxLCIa
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis
    #      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  redis_data:
